WandShop/Web/Controllers/JourneyController.cs
using Logic.Abstract;
using Logic.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
//using System.Web.Mvc;

//using System.Net.Http;
//using System.Web.Http;
//using System.Net;

using Web.Models;
using System.Web.Http.Description;
using System.Web.Http.Results;
using System.Web.Mvc;

namespace Web.Controllers
{
    public class JourneyController : Controller //  ApiController
    {
        private IGameRepository gameRepository;
        private IPlayerPartRepository playerPartRepository;
        private IPlayerRepository playerRepository;
        private IPlayerRoundRepository playerRoundRepository;
        private IRoundRepository roundRepository;

        public JourneyController(
            IGameRepository gameRepository,
            IPlayerPartRepository playerPartRepository,
            IPlayerRepository playerRepository,
            IPlayerRoundRepository playerRoundRepository,
            IRoundRepository roundRepository)
        {
            this.gameRepository = gameRepository;
            this.playerPartRepository = playerPartRepository;
            this.playerRepository = playerRepository;
            this.playerRoundRepository = playerRoundRepository;
            this.roundRepository = roundRepository;
        }
        
        [HttpGet]
        public ActionResult Index()
        {
            var model = new GameListViewModel() { Games = gameRepository.Games.ToList() };
            return View(model);
            //return View(model);
        }
        public ActionResult CreateFullGame()
        {
            return View(new CreateFullGameModel());
        }
        [HttpPost]
        public ActionResult CreateFullGame(CreateFullGameModel model)
        {
            if (ModelState.IsValid)
            {
                Game game = SaveGame(model.ConvertToGame());
                SavePlayers(SavePlayerPartsList(game.GameId, model.PlayersNumber));
                return RedirectToAction("CreateGameParam", new { gameId = game.GameId });
            }
            else
            {
                return View(model);
            }
        }
        public ActionResult CreateGameParam(int gameId)
        {
            return View(new CreateGameParamModel());
        }
        [HttpPost]
        public ActionResult CreateGameParam(CreateGameParamModel model)
        {
            if (ModelState.IsValid)
            {
                SaveGame(SaveGameParams(model));
                return RedirectToAction("Index");
            }
            else
            {
                return View(model);
            }
        }
        public ActionResult Check(int gameId)
        {
            return View(new GameViewModel() { Game = gameRepository.Games.FirstOrDefault(x => x.GameId == gameId) });
        }

        public ActionResult Begin(int gameId)
        {
            if (gameId != 0)
            {
                Game game = gameRepository.Games.FirstOrDefault(x => x.GameId == gameId);
                if (game != null)
                {
                    if (game.CurrentRound == 0)
                    {
                        BeginGame(game);
                    }
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult NextRound(int gameId)
        {
            if (gameId != 0)
            {
                Game game = gameRepository.Games.FirstOrDefault(x => x.GameId == gameId);
                if (game != null)
                {
                    if (game.CurrentRound < game.MaxRounds && game.CurrentRound > 0)
                    {
                        NextRound(game);
                    }
                }
            }
            return RedirectToAction("Index");
        }
        public ActionResult FinishGame(int gameId)
        {
            if (gameId != 0)
            {
                Game game = gameRepository.Games.FirstOrDefault(x => x.GameId == gameId);
                if (game != null)
                {
                    if (game.CurrentRound == game.MaxRounds)
                    {
                        FinishGame(game);
                    }
                }
            }
            return RedirectToAction("Index");
        }


        public Game BeginGame(Game game)
        {
            SaveRound(game.GameId);

            foreach (var pP in game.PlayersPart)
            {
                pP.CurrentRound = 0;
                SavePlayerPart(pP);
                SavePlayerRound(pP, SetStartingRound(pP));
            }
            return SaveGame(UpdateCurrentGameRoundNumber(game));
        }
        private Game NextRound(Game game)
        {
            SaveRound(game.GameId);
            foreach (var pP in game.PlayersPart)
            {
                PlayerRound oldPlayerRound = SavePlayerRound(pP, FinishRound(pP));
                SavePlayerPart(pP);
                PlayerRound newPlayerRound = SavePlayerRound(pP, new PlayerRound());
                newPlayerRound.WandsReservesAmount = oldPlayerRound.WandsReservesAmount;
                SavePlayerRound(pP, SetNextRound(pP, newPlayerRound));
                SavePlayerPart(UpdateCurrentPlayerRoundNumber(pP));
            }
            return SaveGame(UpdateCurrentGameRoundNumber(game));
        }
        private Game FinishGame(Game game)
        {
            foreach (var pP in game.PlayersPart)
            {
                SavePlayerRound(pP, FinishRound(pP));
                playerRepository.DeletePlayer(pP.PlayerPartId);
            }
            Game model = gameRepository.DeleteGame(game.GameId);

            return model;
        }



        #region Helpers

        public Game SaveGame(Game game)
        {
            return gameRepository.SaveGame(game);
        }
        public List<PlayerPart> SavePlayerPartsList(int gameId, int playersNumber)
        {
            return playerPartRepository.AddPlayerParts(gameId, playersNumber).ToList();
        }
        public void SavePlayers(List<PlayerPart> list)
        {
            for (int i = 0; i < list.Count; i++)
            {
                playerRepository.SavePlayer(list[i].PlayerPartId, new Player());
            }
        }
        public Game SaveGameParams(CreateGameParamModel cgpm)
        {
            Game game = gameRepository.Games.FirstOrDefault(x => x.GameId == cgpm.GameId);
            game.Tax = cgpm.Tax;
            game.Dividend = cgpm.Dividend;
            game.OwnContribution = cgpm.OwnContribution;
            game.ForeignShares = cgpm.ForeignShares;
            game.Loan = cgpm.Loan;
            game.InterestRate = cgpm.InterestRate;
            game.ManagementCosts = cgpm.ManagementCosts;
            game.TransportCosts = cgpm.TransportCosts;
            return game;
        }
        public PlayerPart SavePlayerPart(PlayerPart pP)
        {
            return playerPartRepository.SavePlayerPart(pP);
        }
        public PlayerRound SavePlayerRound(PlayerPart pP, PlayerRound round)
        {
            return playerRoundRepository.SavePlayerRound(pP.PlayerPartId, round);
        }
        public void SaveRound(int gameId)
        {
            roundRepository.SaveRound(gameId, new Round());
        }

        public static PlayerRound SetStartingRound(PlayerPart pP)
        {
            return new PlayerRound()
            {
                Gold = pP.Game.OwnContribution + pP.Game.Loan + pP.Game.ForeignShares - pP.Game.BuildingCost,
                LoanRemaining = pP.Game.Loan,
                WoodReserves = 0,
                CrystalReserves = 0,
                WoodPurchased = 0,
                CrystalPurchased = 0,
                WoodAverage = 0,
                CrystalAverage = 0,
                WoodAveragePrevious = 0,
                CrystalAveragePrevious = 0,
                MachinesOwned = 0,
                MachinesPurchased = 0,
                MachinesSold = 0,
                DwarfWorkers = 0,
                ElfWorkers = 0,
                HumanWorkers = 0,
                DwarfWorkersEmployed = 0,
                ElfWorkersEmployed = 0,
                HumanWorkersEmployed = 0,
                DwarfWorkersDismissed = 0,
                ElfWorkersDismissed = 0,
                HumanWorkersDismissed = 0,
                QualityExpense = 0,
                AdExpense = 0,
                QualityExpensePrevious = 0,
                AdExpensePrevious = 0,
                LoanPaid = 0,
                LoanTaken = 0,
                WandsProducedAmount = 0,
                WandPrice = 0,
                WandsSoldAmount = 0,
                Income = 0,
                WandsReservesAmount = 0,
                PlayerRoundNumber = 1
            };
        }
        public static PlayerRound FinishRound(PlayerPart pP)
        {
            PlayerRound pr = new PlayerRound();

            pr.PlayerPartId = pP.PlayerPartId;
            pr.PlayerPart = pP;
            pr.PlayerRoundId = pP.PlayerRounds[pP.CurrentRound].PlayerRoundId;
            pr.Gold = pP.PlayerRounds[pP.CurrentRound].Gold;
            pr.LoanRemaining = pP.PlayerRounds[pP.CurrentRound].LoanRemaining;
            pr.WoodReserves = pP.PlayerRounds[pP.CurrentRound].WoodReserves;
            pr.CrystalReserves = pP.PlayerRounds[pP.CurrentRound].CrystalReserves;
            pr.WoodPurchased = pP.PlayerRounds[pP.CurrentRound].WoodPurchased;
            pr.CrystalPurchased = pP.PlayerRounds[pP.CurrentRound].CrystalPurchased;
            pr.WoodAveragePrevious = pP.PlayerRounds[pP.CurrentRound].WoodAveragePrevious;
            pr.CrystalAveragePrevious = pP.PlayerRounds[pP.CurrentRound].CrystalAveragePrevious;
            pr.MachinesOwned = pP.PlayerRounds[pP.CurrentRound].MachinesOwned;
            pr.MachinesPurchased = pP.PlayerRounds[pP.CurrentRound].MachinesPurchased;
            pr.MachinesSold = pP.PlayerRounds[pP.CurrentRound].MachinesSold;
            pr.DwarfWorkers = pP.PlayerRounds[pP.CurrentRound].DwarfWorkers;

WandShop/Web/Views/Journey/Check.cshtml
@model Web.Models.GameViewModel

@{
    ViewBag.Title = "Gra";
}

<h2>Co chcesz zrobić z grą?</h2>
@Model.Game.GameId
<div>
    @Html.ActionLink("Rozpocznik grę", "Begin", new { Model.Game.GameId }, new { @class = "btn btn-default" })
</div>
<div>
    @Html.ActionLink("Następna runda", "NextRound", new { Model.Game.GameId }, new { @class = "btn btn-default" })
</div>
<div>
    @Html.ActionLink("Zakończ grę", "FinishGame", new { Model.Game.GameId }, new { @class = "btn btn-default" })
</div>
<div>
    @Html.ActionLink("Anuluj i wróc do listy", "Index", null, new { @class = "btn btn-default" })
</div>

WandShop/Web/Views/Journey/CreateFullGame.cshtml
@model Web.Models.CreateFullGameModel

@{
    ViewBag.Title = "CreateFullGame";
}

<h2>Dodaj grę</h2>
@using (Html.BeginForm("CreateFullGame", "Journey"))
{
    <div class="panel-body">
        @Html.HiddenFor(x => x.GameId)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {
            <div class="form-group">
                @if (property.PropertyName != "GameId" && property.PropertyName != "CreateGameParamModel")
                {
                    <label>@(property.DisplayName ?? property.PropertyName)</label>
                        @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                        @Html.ValidationMessage(property.PropertyName)
                }
            </div>
        }
    </div>
    <input type="submit" value="Dodaj" class="btn btn-primary" />
    @Html.ActionLink("Anuluj i wróc do listy", "Index", null, new { @class = "btn btn-default" })
}

WandShop/Web/Views/Journey/CreateGameParam.cshtml
@model Web.Models.CreateGameParamModel

@{
    ViewBag.Title = "Dostosuj swoją grę!";
}

<h2>Dostosuj swoją grę!</h2>

@using (Html.BeginForm("CreateGameParam", "Journey"))
{
    <div class="panel-body">
        @Html.HiddenFor(x => x.GameId)
        @foreach (var property in ViewData.ModelMetadata.Properties)
        {

            <div class="form-group">
                @if (property.PropertyName != "GameId" && property.PropertyName != "CreateGameParamModel")
                {
                    <label>@(property.DisplayName ?? property.PropertyName)</label>
                    @Html.TextBox(property.PropertyName, null, new { @class = "form-control" })
                    @Html.ValidationMessage(property.PropertyName)
                }
            </div>
        }
    </div>
    <input type="submit" value="Dostosuj grę!" class="btn btn-primary" />
    <div class="btn">
        <!-- co tu nie działa? -->
        @Html.ActionLink("Zostaw wartości domyślne", "Index")
    </div>
}

WandShop/Web/Views/Journey/Index.cshtml
<script>
    //fetch('Journey/Index')
    //.then((response) =>
    //{ return response.json() })
    //.then((json) =>
    //{console.log(json) })
</script>
@model Web.Models.GameListViewModel

@{
    ViewBag.Title = "Lista Twoich gier";
}

<h2>Pełna lista gier</h2>
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th scope="col">Id gry</th>
            <th scope="col">Max liczba rund</th>
            <th scope="col">Aktualna runda</th>
            <th scope="col">Ilość graczy</th>
            <th scope="col">Sprawdź szczegóły</th>
        </tr>
    </thead>
    @foreach (var item in Model.Games)
    {
        <tr>
            <td>@item.GameId</td>
            <td>@item.MaxRounds</td>
            <td>@item.CurrentRound</td>
            <td>@item.PlayersPart.Count</td>
            <td>@Html.ActionLink("Sprawdź", "Check", new { gameId = item.GameId })</td>
        </tr>
    }
</table>

@Html.ActionLink("Dodaj grę", "CreateFullGame", null, new { @class = "btn-group" })