WandShop/Web/Models/GameViewModel.cs
using Logic.Entities;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Web.Models
{
    public class GameViewModel
    {
        public Game Game { get; set; }
    }
}

WandShop/Web/Controllers/ExploreController.cs
using Logic.Abstract;
using Logic.Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Web.Models;
using Web.Helpers;

namespace Web.Controllers
{
    public class ExploreController : Controller
    {
        private IGameRepository gameRepository;
        private IPlayerPartRepository playerPartRepository;
        private IPlayerRepository playerRepository;
        private IPlayerRoundRepository playerRoundRepository;
        private IRoundRepository roundRepository;

        public ExploreController(
            IGameRepository gameRepository,
            IPlayerPartRepository playerPartRepository,
            IPlayerRepository playerRepository,
            IPlayerRoundRepository playerRoundRepository,
            IRoundRepository roundRepository)
        {
            this.gameRepository = gameRepository;
            this.playerPartRepository = playerPartRepository;
            this.playerRepository = playerRepository;
            this.playerRoundRepository = playerRoundRepository;
            this.roundRepository = roundRepository;
        }

        public ActionResult Index()
        {
            if (AccessFirst())
                return View("Act");
            return View();
        }
        [HttpPost]
        public ActionResult Authorize(Player player)
        {
            if(player != null)
            {
                Player p = playerRepository.Players.Where(x => x.Login == player.Login && x.Password == player.Password).FirstOrDefault();
                if (p != null)
                {
                    Session["PlayerId"] = p.PlayerId;
                    return RedirectToAction("Act"); 
                }
            }
            return View("Index");
        }
        public ActionResult Act()
        {
            if(!AccessFirst())
                return View("Index");

            return View();
        }
        public ActionResult Games()
        {
            if (!AccessFirst())
                return View("Index");
            return View(new PlayerRoundsViewModel(playerPartRepository.PlayerParts.FirstOrDefault(x => x.PlayerPartId == (int)Session["PlayerId"]).PlayerRounds));
        }
        public ActionResult Round(int playerRoundIndex)
        {
            if (!AccessFirst())
                return View("Index");

            PlayerRound pr = playerRoundRepository.PlayerRounds.FirstOrDefault(x => x.PlayerRoundId == playerRoundIndex);

            if (pr == null)
                return RedirectToAction("Games");

            if (pr.PlayerPartId != (int)Session["PlayerId"])
                return RedirectToAction("Games");

            PlayerRoundViewModel prvm = new PlayerRoundViewModel(pr);
            return View(prvm);
        }
        public ActionResult Play()
        {
            if (!AccessFirst())
                return View("Index");

            PlayerPart pr = playerPartRepository.PlayerParts.FirstOrDefault(x => x.PlayerPartId == (int)Session["PlayerId"]);
            if (pr.PlayerRounds.Count == 0)
                return RedirectToAction("Act");

            PlayerPlayRoundModel pprm = new PlayerPlayRoundModel(pr);
            return View(pprm);
        }
        [HttpPost]
        public ActionResult Play(PlayerPlayRoundModel model)
        {
            if (!AccessFirst())
                return View("Index");
            if (ModelState.IsValid )
            {
                PlayerPart pp = playerPartRepository.PlayerParts.FirstOrDefault(x => x.PlayerPartId == (int)Session["PlayerId"]);

                model.SetLoanRemaining(pp.PlayerRounds[pp.CurrentRound].LoanRemaining);
                model.ValidationMes = new List<string>();
                model.ValidationMes = Validation.PlayerPlayRoundValidation(model, pp);
                if(model.ValidationMes.Count == 0)
                {
                    SavePlayerPart(pp, UpdatePlayerRound(pp, model));
                    return View("Act");
                }
                else
                {
                    PlayerPlayRoundModel pprm = new PlayerPlayRoundModel(playerPartRepository.PlayerParts.FirstOrDefault(x => x.PlayerPartId == (int)Session["PlayerId"]), model);
                    return View(pprm);
                }

            }
            else
            {
                PlayerPlayRoundModel pprm = new PlayerPlayRoundModel(playerPartRepository.PlayerParts.FirstOrDefault(x => x.PlayerPartId == (int)Session["PlayerId"]), model);
                return View(pprm);
            }
        }
        public ActionResult Logout()
        {
            Session.Abandon();
            return View("Index");
        }

        private bool AccessFirst()
        {
            //int id = playerRepository.Players.FirstOrDefault(x => x.PlayerId == (int)Session["PlayerId"]).PlayerId;

            if (Session["PlayerId"] == null || (int)Session["PlayerId"] == 0)
                return false;
            return true;
        }

        #region Helpers
        public static PlayerRound UpdatePlayerRound(PlayerPart pP, PlayerPlayRoundModel pprm)
        {
            PlayerRound pr = pP.PlayerRounds[pP.CurrentRound];
            pr.WoodPurchased = pprm.WoodPurchased;
            pr.CrystalPurchased = pprm.CrystalPurchased;
            pr.MachinesPurchased = pprm.MachinesPurchased;
            pr.DwarfWorkersEmployed = pprm.DwarfWorkersEmployed;
            pr.ElfWorkersEmployed = pprm.ElfWorkersEmployed;
            pr.HumanWorkersEmployed = pprm.HumanWorkersEmployed;
            pr.DwarfWorkersDismissed = pprm.DwarfWorkersDismissed;
            pr.ElfWorkersDismissed = pprm.ElfWorkersDismissed;
            pr.HumanWorkersDismissed = pprm.HumanWorkersDismissed;
            pr.QualityExpense = pprm.QualityExpense;
            pr.AdExpense = pprm.AdExpense;
            pr.LoanPaid = pprm.LoanPaid;
            pr.LoanTaken = pprm.LoanTaken;
            pr.WandPrice = pprm.WandPrice;
            pr.WandsProducedAmount = pprm.WandsProducedAmount;
            return pr;
        }
        public PlayerRound SavePlayerPart(PlayerPart pP, PlayerRound pr)
        {
            return playerRoundRepository.SavePlayerRound(pP.PlayerPartId, pr);
        }
        #endregion
    }
}

WandShop/Web/Views/Explore/Act.cshtml
@{
    ViewBag.Title = "Act";
}

<h2>Jesteś zalogowany</h2>
@Html.ActionLink("Archiwum", "Games")
@Html.ActionLink("Graj!", "Play")
@Html.ActionLink("Wyloguj się", "Logout")

WandShop/Web/Views/Explore/Games.cshtml
@model Web.Models.PlayerRoundsViewModel

@{
    ViewBag.Title = "Games";
}

<h2>Games</h2>

<table class="table">
    <tr>
        <th>
            Numer rundy
        </th>
        <th>
            Szczegóły
        </th>
    </tr>
@foreach (var item in Model.PlayerRoundStructs) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PlayerRoundNumber)
        </td>
        <td>
            @Html.ActionLink("Sprawdź","Round", new { playerRoundIndex  = item.PlayerRoundId})
        </td>
    </tr>
}
</table>

WandShop/Web/Views/Explore/Index.cshtml
@model Logic.Entities.Player
@{
    ViewBag.Title = "Logowanie";
}
@using (Html.BeginForm("Authorize", "Explore", FormMethod.Post))
{
    <table>
        <tr>
            <td></td>
            <td>Login</td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(Model => Model.Login)
            </td>
            <td>
                @Html.EditorFor(Model => Model.Login)
            </td>
        </tr>
        <tr>
            <td>
                @Html.LabelFor(Model => Model.Password)
            </td>
            <td>
                @Html.EditorFor(Model => Model.Password)
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" name="name" value="Login" />
            </td>
        </tr>
    </table>
}

WandShop/Web/Views/Explore/Play.cshtml
@model Web.Models.PlayerPlayRoundModel

@{
    ViewBag.Title = "Play";
}

<h2>Play</h2>

@if(Model.ValidationMes.Count != 0)
{
    <h2>Błędy:</h2>
    <ul>
        @foreach (var item in Model.ValidationMes)
        {
            <li>
                @item
            </li>
        }
    </ul>
}

@using (Html.BeginForm("Play", "Explore"))
{
    @Html.AntiForgeryToken()


    @Html.HiddenFor(x => x.PlayerPartId)
    <div class="form-horizontal">
        <h4>PlayerPlayRoundModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.WoodPurchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WoodPurchased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WoodPurchased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.CrystalPurchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CrystalPurchased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CrystalPurchased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.MachinesPurchased, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MachinesPurchased, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MachinesPurchased, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DwarfWorkersEmployed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DwarfWorkersEmployed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DwarfWorkersEmployed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElfWorkersEmployed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElfWorkersEmployed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElfWorkersEmployed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HumanWorkersEmployed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HumanWorkersEmployed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HumanWorkersEmployed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.DwarfWorkersDismissed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.DwarfWorkersDismissed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DwarfWorkersDismissed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ElfWorkersDismissed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ElfWorkersDismissed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ElfWorkersDismissed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.HumanWorkersDismissed, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.HumanWorkersDismissed, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.HumanWorkersDismissed, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.QualityExpense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.QualityExpense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.QualityExpense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdExpense, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdExpense, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdExpense, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoanPaid, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoanPaid, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoanPaid, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LoanTaken, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LoanTaken, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LoanTaken, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WandPrice, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WandPrice, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WandPrice, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.WandsProducedAmount, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.WandsProducedAmount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.WandsProducedAmount, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

WandShop/Web/Views/Explore/Round.cshtml
@model Web.Models.PlayerRoundViewModel

@{
    ViewBag.Title = "Round";
}

<h2>Round</h2>
<div class="panel-body">
    @foreach (var property in ViewData.ModelMetadata.Properties)
    {
        <div class="form-group">
            <label>@(property.DisplayName ?? property.PropertyName)</label>
            @Html.Label(property.Model.ToString(), null, new { @class = "form-control" })
        </div>
    }
</div>
<div>
    @Html.ActionLink("Wróć", "Games", null ,new { @class = "btn btn-primary" })
</div>